Parse the Xref.text file to make a record for each line in separate lists

In [0]:
import sys
import re
feature_AC = [] # create a list which we will use to store data
feature_AC_specialDR1 = []
feature_AC_specialDR2 = []
feature_AC_specialDR3 = []
feature_DR1 = []
feature_DR2 = []
feature_DR3 = [] 
numentries = 0
numentriesSpecialDR1 = 0
numentriesSpecialDR2 = 0
numentriesSpecialDR3 = 0
with open('Xref_September.txt', 'r') as infile:
    for line in infile:
        if line.startswith('AC'):
            AC = infile.readline().rstrip()         
            FROM = infile.readline().rstrip()
            DR1 = infile.readline().rstrip()        
            TO = infile.readline().rstrip()
            if 'TO' in TO:         
                #print(TO)
                DR2 = infile.readline().rstrip()
                if DR2.startswith("DR"):
                    fine =infile.readline().rstrip()
                    if fine.startswith('DR'):
                        feature_AC_specialDR2.append(AC)
                        numentriesSpecialDR2 = numentriesSpecialDR2 + 1
                        #print("found")
                    else:
                        feature_AC.append(AC)
                        feature_DR1.append(DR1)
                        feature_DR2.append(DR2) 
                        numentries = numentries + 1
                else:
                    feature_AC_specialDR3.append(AC)
                    numentriesSpecialDR3 = numentriesSpecialDR3 + 1
            else:
                feature_AC_specialDR1.append(AC)
                numentriesSpecialDR1 = numentriesSpecialDR1 + 1

print(feature_AC, feature_DR1, feature_DR2)
print(numentries, numentriesSpecialDR1, numentriesSpecialDR2, numentriesSpecialDR3)
print(feature_AC_specialDR1, feature_AC_specialDR2, feature_AC_specialDR3)

['Q9VMV6', 'Q9VQN8', 'Q9NJH0', 'Q8MSF5', 'A1ZBW7', 'P05303', 'Q9Y169', 'Q9VAP3', 'A2VEI2', 'Q9V3U0', 'Q9V4W1', 'Q9VMH0', 'P42281', 'Q9VKD3', 'P13060', 'Q9VK41', 'Q9Y105', 'Q9VE09', 'Q9VUQ8', 'Q9VKN7', 'Q9Y117', 'Q9I7S8', 'Q9W1H4', 'Q9VES1', 'P37193', 'P22700', 'Q9VV43', 'P54397', 'Q27580', 'P13098', 'Q9VCP1', 'Q9VH95', 'Q9VE34', 'Q9VM33', 'P35421', 'P50245', 'Q9VUT6', 'Q8MV48', 'P56079', 'Q9VBX2', 'Q7JUX9', 'Q9VC99', 'Q9VW09', 'Q7KQM6', 'Q24407', 'Q94517', 'Q9VH36', 'Q7K4B6', 'Q9VLL0', 'Q9W141', 'Q9VKK2', 'Q9VP47', 'Q9VLM5', 'Q9VGC3', 'Q9VLM8', 'Q9VTM0', 'O77264', 'P00967', 'Q9VJ97', 'Q9VHV5', 'Q9VQX4', 'Q9VVA8', 'Q95028', 'Q9VRJ2', 'Q9W5N0', 'Q8IA42', 'Q9VAI0', 'Q9W2Y3', 'Q8T8R1', 'Q9V9A7', 'A1ZAG4', 'Q9VT67', 'Q9VUY9', 'P13706', 'Q9VCE6', 'P48375', 'Q24572', 'Q9VYQ0', 'Q09332', 'Q6WV17', 'Q6WV16', 'Q6WV19', 'P0C919', 'Q7K4H4', 'Q9VL78', 'Q9VYA0', 'Q8MT36', 'Q9VFL5', 'O77475', 'Q9VYR0', 'P20007', 'Q9VSF3', 'Q6WV20', 'Q7KVH9', 'Q9VD92', 'Q02360', 'Q9VBV5', 'Q9VCX4', 'Q9W1A2', 'Q9VGP0', 'Q9VZE7', 'B7Z0W9', 'Q9VTZ6', 'Q9VLJ8', 'Q9VWP4', 'Q8IQ70', 'Q94522'] ['DR   FlyBase; FBgn0031670; CG3887.', 'DR   FlyBase; FBgn0031519; CG3326.', 'DR   FlyBase; FBgn0029176; Ef1gamma.', 'DR   FlyBase; FBgn0262116; CG40127.', 'DR   FlyBase; FBgn0034529; CG16742.', 'DR   FlyBase; FBgn0000557; Ef1alpha100E.', 'DR   FlyBase; FBgn0029175; Ext2.', 'DR   FlyBase; FBgn0039637; CG11880.', 'DR   FlyBase; FBgn0031893; CG4495.', 'DR   FlyBase; FBgn0028519; CG4500.', 'DR   FlyBase; FBgn0033316; CG14749.', 'DR   FlyBase; FBgn0261697; tectonic.', 'DR   FlyBase; FBgn0010387; Dbi.', 'DR   FlyBase; FBgn0032393; CG12264.', 'DR   FlyBase; FBgn0000559; EF2.', 'DR   FlyBase; FBgn0032470; CG5142.', 'DR   FlyBase; FBgn0027090; Aats-gln.', 'DR   FlyBase; FBgn0260779; gatA.', 'DR   FlyBase; FBgn0036510; CG7427.', 'DR   FlyBase; FBgn0024227; ial.', 'DR   FlyBase; FBgn0027558; pgant3.', 'DR   FlyBase; FBgn0020513; ade5.', 'DR   FlyBase; FBgn0262619; DNA-ligI.', 'DR   FlyBase; FBgn0038453; CG10326.', 'DR   FlyBase; FBgn0011769; Fdxh.', 'DR   FlyBase; FBgn0263006; Ca-P60A.', 'DR   FlyBase; FBgn0266417; CG45057.', 'DR   FlyBase; FBgn0013269; FK506-bp1.', 'DR   FlyBase; FBgn0014455; Ahcy13.', 'DR   FlyBase; FBgn0000591; E(spl).', 'DR   FlyBase; FBgn0039065; CG4449.', 'DR   FlyBase; FBgn0037728; CG16817.', 'DR   FlyBase; FBgn0038651; CG14299.', 'DR   FlyBase; FBgn0263133; ico.', 'DR   FlyBase; FBgn0000052; ade2.', 'DR   FlyBase; FBgn0015011; Ahcy89E.', 'DR   FlyBase; FBgn0036529; pgant8.', 'DR   FlyBase; FBgn0030930; GalNAc-T2.', 'DR   FlyBase; FBgn0010350; CdsA.', 'DR   FlyBase; FBgn0039280; Mocs2.', 'DR   FlyBase; FBgn0034351; CG5190.', 'DR   FlyBase; FBgn0263398; CG6364.', 'DR   FlyBase; FBgn0262517; l(3)76BDr.', 'DR   FlyBase; FBgn0039936; CG11148.', 'DR   FlyBase; FBgn0016119; ATPsynCf6.', 'DR   FlyBase; FBgn0015805; Rpd3.', 'DR   FlyBase; FBgn0037780; CG3925.', 'DR   FlyBase; FBgn0020312; CG4050.', 'DR   FlyBase; FBgn0027780; U26.', 'DR   FlyBase; FBgn0035032; CG4692.', 'DR   FlyBase; FBgn0032339; CG4705.', 'DR   FlyBase; FBgn0037073; CG7338.', 'DR   FlyBase; FBgn0263852; l(2)k12914.', 'DR   FlyBase; FBgn0037998; CG4848.', 'DR   FlyBase; FBgn0027094; Aats-ala.', 'DR   FlyBase; FBgn0036192; Pallidin.', 'DR   FlyBase; FBgn0025630; CG4061.', 'DR   FlyBase; FBgn0000053; ade3.', 'DR   FlyBase; FBgn0032671; CG7200.', 'DR   FlyBase; FBgn0037551; Gie.', 'DR   FlyBase; FBgn0031589; CG3714.', 'DR   FlyBase; FBgn0036667; CG9669.', 'DR   FlyBase; FBgn0001258; ImpL3.', 'DR   FlyBase; FBgn0035586; CG10671.', 'DR   FlyBase; FBgn0039965; CG13865.', 'DR   FlyBase; FBgn0051956; pgant4.', 'DR   FlyBase; FBgn0039690; CG1969.', 'DR   FlyBase; FBgn0030178; CG2974.', 'DR   FlyBase; FBgn0034802; CG3800.', 'DR   FlyBase; FBgn0042083; CG3267.', 'DR   FlyBase; FBgn0034129; CG15925.', 'DR   FlyBase; FBgn0036057; CG14164.', 'DR   FlyBase; FBgn0003076; Pgm.', 'DR   FlyBase; FBgn0001128; Gpdh.', 'DR   FlyBase; FBgn0039139; Ime4.', 'DR   FlyBase; FBgn0013954; FK506-bp2.', 'DR   FlyBase; FBgn0263979; Caf1.', 'DR   FlyBase; FBgn0030373; CG12721.', 'DR   FlyBase; FBgn0014075; Ugt.', 'DR   FlyBase; FBgn0031681; pgant5.', 'DR   FlyBase; FBgn0035375; pgant6.', 'DR   FlyBase; FBgn0031530; pgant2.', 'DR   FlyBase; FBgn0260229; CG42503.', 'DR   FlyBase; FBgn0266570; CG2982.', 'DR   FlyBase; FBgn0029174; FKBP59.', 'DR   FlyBase; FBgn0030512; CG9940.', 'DR   FlyBase; FBgn0039559; Mes-4.', 'DR   FlyBase; FBgn0027083; Aats-met-m.', 'DR   FlyBase; FBgn0025335; CG4585.', 'DR   FlyBase; FBgn0030364; CG15735.', 'DR   FlyBase; FBgn0003067; Pepck.', 'DR   FlyBase; FBgn0035853; Ubc12.', 'DR   FlyBase; FBgn0034025; GalNAc-T1.', 'DR   FlyBase; FBgn0034894; CG4091.', 'DR   FlyBase; FBgn0038893; CG6353.', 'DR   FlyBase; FBgn0004895; fd64A.', 'DR   FlyBase; FBgn0039296; CG10420.', 'DR   FlyBase; FBgn0051159; EF-G2.', 'DR   FlyBase; FBgn0034982; CG4065.', 'DR   FlyBase; FBgn0037898; CG18643.', 'DR   FlyBase; FBgn0035523; CG1311.', 'DR   FlyBase; FBgn0259150; CG42265.', 'DR   FlyBase; FBgn0036300; CG10688.', 'DR   FlyBase; FBgn0032054; CG13090.', 'DR   FlyBase; FBgn0030966; CG7280.', 'DR   FlyBase; FBgn0042185; CG18769.', 'DR   FlyBase; FBgn0004888; Scsalpha.'] ['DR   FlyBase; FBgn0031670; SelT.', 'DR   FlyBase; FBgn0031519; Fign.', 'DR   FlyBase; FBgn0029176; eEF1gamma.', 'DR   FlyBase; FBgn0262116; RNASEK.', 'DR   FlyBase; FBgn0034529; FAM21.', 'DR   FlyBase; FBgn0000557; eEF1alpha2.', 'DR   FlyBase; FBgn0029175; sotv.', 'DR   FlyBase; FBgn0039637; Ctl2.', 'DR   FlyBase; FBgn0031893; MICU1.', 'DR   FlyBase; FBgn0028519; hll.', 'DR   FlyBase; FBgn0033316; Gle1.', 'DR   FlyBase; FBgn0261697; tctn.', 'DR   FlyBase; FBgn0010387; Acbp2.', 'DR   FlyBase; FBgn0032393; Nfs1.', 'DR   FlyBase; FBgn0000559; eEF2.', 'DR   FlyBase; FBgn0032470; Ttc30.', 'DR   FlyBase; FBgn0027090; GlnRS.', 'DR   FlyBase; FBgn0260779; GatA.', 'DR   FlyBase; FBgn0036510; SCCRO.', 'DR   FlyBase; FBgn0024227; aurB.', 'DR   FlyBase; FBgn0027558; Pgant3.', 'DR   FlyBase; FBgn0020513; Paics.', 'DR   FlyBase; FBgn0262619; DNAlig1.', 'DR   FlyBase; FBgn0038453; Arl6IP1.', 'DR   FlyBase; FBgn0011769; Fdx1.', 'DR   FlyBase; FBgn0263006; SERCA.', 'DR   FlyBase; FBgn0266417; ringer.', 'DR   FlyBase; FBgn0013269; Fkbp39.', 'DR   FlyBase; FBgn0014455; Ahcy.', 'DR   FlyBase; FBgn0000591; E(spl)m8-HLH.', 'DR   FlyBase; FBgn0039065; Rad60.', 'DR   FlyBase; FBgn0037728; p23.', 'DR   FlyBase; FBgn0038651; Epg5.', 'DR   FlyBase; FBgn0263133; mEFG1.', 'DR   FlyBase; FBgn0000052; Pfas.', 'DR   FlyBase; FBgn0015011; AhcyL2.', 'DR   FlyBase; FBgn0036529; Pgant8.', 'DR   FlyBase; FBgn0030930; Pgant7.', 'DR   FlyBase; FBgn0010350; Cds.', 'DR   FlyBase; FBgn0039280; Mocs2B.', 'DR   FlyBase; FBgn0034351; rswl.', 'DR   FlyBase; FBgn0263398; Uck.', 'DR   FlyBase; FBgn0262517; Ltn1.', 'DR   FlyBase; FBgn0039936; Gyf.', 'DR   FlyBase; FBgn0016119; ATPsynCF6.', 'DR   FlyBase; FBgn0015805; HDAC1.', 'DR   FlyBase; FBgn0037780; ohgt.', 'DR   FlyBase; FBgn0020312; Tmtc3.', 'DR   FlyBase; FBgn0027780; Aasdh.', 'DR   FlyBase; FBgn0035032; ATPsynF.', 'DR   FlyBase; FBgn0032339; Wdr59.', 'DR   FlyBase; FBgn0037073; Tsr1.', 'DR   FlyBase; FBgn0263852; Dad1.', 'DR   FlyBase; FBgn0037998; Cog1.', 'DR   FlyBase; FBgn0027094; AlaRS.', 'DR   FlyBase; FBgn0036192; Pldn.', 'DR   FlyBase; FBgn0025630; Rtca.', 'DR   FlyBase; FBgn0000053; Gart.', 'DR   FlyBase; FBgn0032671; JMJD4.', 'DR   FlyBase; FBgn0037551; Arl8.', 'DR   FlyBase; FBgn0031589; Naprt.', 'DR   FlyBase; FBgn0036667; kud.', 'DR   FlyBase; FBgn0001258; Ldh.', 'DR   FlyBase; FBgn0035586; Fitm.', 'DR   FlyBase; FBgn0039965; Coa7.', 'DR   FlyBase; FBgn0051956; Pgant4.', 'DR   FlyBase; FBgn0039690; Gnpnat.', 'DR   FlyBase; FBgn0030178; Naxe.', 'DR   FlyBase; FBgn0034802; CNBP.', 'DR   FlyBase; FBgn0042083; Mccc2.', 'DR   FlyBase; FBgn0034129; Parp16.', 'DR   FlyBase; FBgn0036057; Hez.', 'DR   FlyBase; FBgn0003076; Pgm1.', 'DR   FlyBase; FBgn0001128; Gpdh1.', 'DR   FlyBase; FBgn0039139; Mettl3.', 'DR   FlyBase; FBgn0013954; Fkbp12.', 'DR   FlyBase; FBgn0263979; Caf1-55.', 'DR   FlyBase; FBgn0030373; moon.', 'DR   FlyBase; FBgn0014075; Uggt.', 'DR   FlyBase; FBgn0031681; Pgant5.', 'DR   FlyBase; FBgn0035375; Pgant6.', 'DR   FlyBase; FBgn0031530; Pgant2.', 'DR   FlyBase; FBgn0260229; Mocs2A.', 'DR   FlyBase; FBgn0266570; NO66.', 'DR   FlyBase; FBgn0029174; Fkbp59.', 'DR   FlyBase; FBgn0030512; Nadsyn.', 'DR   FlyBase; FBgn0039559; NSD.', 'DR   FlyBase; FBgn0027083; MetRS-m.', 'DR   FlyBase; FBgn0025335; Cpes.', 'DR   FlyBase; FBgn0030364; Lsm12.', 'DR   FlyBase; FBgn0003067; Pepck1.', 'DR   FlyBase; FBgn0035853; UbcE2M.', 'DR   FlyBase; FBgn0034025; Pgant1.', 'DR   FlyBase; FBgn0034894; sigmar.', 'DR   FlyBase; FBgn0038893; Archease.', 'DR   FlyBase; FBgn0004895; FoxL1.', 'DR   FlyBase; FBgn0039296; Sil1.', 'DR   FlyBase; FBgn0051159; mRRF2.', 'DR   FlyBase; FBgn0034982; Naa35.', 'DR   FlyBase; FBgn0037898; Dtd.', 'DR   FlyBase; FBgn0035523; Ctl1.', 'DR   FlyBase; FBgn0259150; OtopLc.', 'DR   FlyBase; FBgn0036300; Pmm2.', 'DR   FlyBase; FBgn0032054; Uba4.', 'DR   FlyBase; FBgn0030966; Suox.', 'DR   FlyBase; FBgn0042185; MCU.', 'DR   FlyBase; FBgn0004888; Scsalpha1.']
107 3 5 161
['Q7KV12', 'Q70PU2', 'P84054'] ['P67807', 'C0HK98', 'Q70PU1', 'C0HKQ7', 'C0HKF7'] ['O16053', 'P24516', 'P25727', 'Q23834', 'Q27638', 'Q9NBX4', 'Q9NBX5', 'P67804', 'Q9U4X4', 'Q9U4X3', 'P50266', 'Q6XHI1', 'P54629', 'P54628', 'P54627', 'Q9V4U7', 'B4KBH3', 'O44535', 'P54624', 'B4M3C9', 'Q25109', 'P09145', 'P13729', 'P54630', 'Q6XI71', 'P11424', 'P17645', 'Q7KHA1', 'P17646', 'P16320', 'B4LQ44', 'Q24705', 'P41876', 'P83757', 'P07735', 'O46254', 'P20828', 'P20829', 'P20825', 'P28487', 'Q6XIN1', 'P28485', 'P56674', 'B4KR21', 'P13427', 'Q8I7P9', 'P83130', 'P17111', 'P84222', 'P04282', 'P04283', 'O46236', 'P23241', 'P51552', 'A4UM12', 'P39806', 'Q9NHP5', 'Q05487', 'Q08876', 'Q9NHP7', 'P12349', 'Q24735', 'Q24738', 'Q24739', 'A4UM19', 'P26620', 'O16811', 'O16812', 'A4UM16', 'O17482', 'Q03297', 'P55924', 'Q03295', 'Q24741', 'Q24742', 'Q24746', 'P83950', 'P25988', 'Q02638', 'P83833', 'Q6V3V8', 'P29304', 'P04146', 'Q08171', 'Q5W1L4', 'Q24761', 'Q24751', 'Q24753', 'P10394', 'Q8ISC9', 'P12258', 'Q24762', 'Q8I1H7', 'Q24767', 'P59597', 'P10403', 'Q07182', 'P10405', 'P10401', 'Q00670', 'Q26288', 'Q27135', 'P10094', 'Q7M3K2', 'P10095', 'Q27928', 'O18638', 'C0HKA5', 'C0HKA6', 'P30107', 'Q95SX7', 'Q95ZE9', 'Q8I1F0', 'P84328', 'P0CU29', 'P01372', 'P0DKM0', 'P54365', 'P54363', 'Q9N6K2', 'Q8I7Q0', 'Q8I145', 'P23194', 'O02008', 'Q24332', 'Q9GRW7', 'Q24331', 'P21329', 'P21328', 'C0HL63', 'Q95087', 'Q95NT6', 'C0HL62', 'P04323', 'Q9NBL2', 'P20806', 'Q9BI23', 'O76265', 'O76264', 'P16425', 'O76263', 'P16424', 'P16423', 'O44219', 'P84181', 'P84295', 'Q967S7', 'P21331', 'P21330', 'P60319', 'Q9BI17', 'Q23933', 'Q23935', 'B4NP05', 'O18602', 'O18601', 'Q9U6A1', 'O77458', 'P58249', 'Q7M3M6', 'Q7JQ07']

Exctract information new gene name from the feature_DR2 list.

In [0]:
import re

myl = feature_DR2
newgene_name = []
for element in myl:
    m = re.match(r'DR.+[\w.]+;\s[\w.]+;\s+(\w.*)\.', element)
    if m:
        found = m.group(1)
        newgene_name.append(found)
#newgene_name
len(newgene_name)

107

In [0]:
len(feature_AC)

107

In [0]:
import re

myl = feature_DR2
print(myl)
newFGgene_name = []
for element in myl:
    m = re.match(r'DR.+[\w.]+;\s(FBgn\d+);\s+(\w.*)\.', element)
    if m:
        found = m.group(1)
        newFGgene_name.append(found)
#newFGgene_name
len(newFGgene_name)

['DR   FlyBase; FBgn0031670; SelT.', 'DR   FlyBase; FBgn0031519; Fign.', 'DR   FlyBase; FBgn0029176; eEF1gamma.', 'DR   FlyBase; FBgn0262116; RNASEK.', 'DR   FlyBase; FBgn0034529; FAM21.', 'DR   FlyBase; FBgn0000557; eEF1alpha2.', 'DR   FlyBase; FBgn0029175; sotv.', 'DR   FlyBase; FBgn0039637; Ctl2.', 'DR   FlyBase; FBgn0031893; MICU1.', 'DR   FlyBase; FBgn0028519; hll.', 'DR   FlyBase; FBgn0033316; Gle1.', 'DR   FlyBase; FBgn0261697; tctn.', 'DR   FlyBase; FBgn0010387; Acbp2.', 'DR   FlyBase; FBgn0032393; Nfs1.', 'DR   FlyBase; FBgn0000559; eEF2.', 'DR   FlyBase; FBgn0032470; Ttc30.', 'DR   FlyBase; FBgn0027090; GlnRS.', 'DR   FlyBase; FBgn0260779; GatA.', 'DR   FlyBase; FBgn0036510; SCCRO.', 'DR   FlyBase; FBgn0024227; aurB.', 'DR   FlyBase; FBgn0027558; Pgant3.', 'DR   FlyBase; FBgn0020513; Paics.', 'DR   FlyBase; FBgn0262619; DNAlig1.', 'DR   FlyBase; FBgn0038453; Arl6IP1.', 'DR   FlyBase; FBgn0011769; Fdx1.', 'DR   FlyBase; FBgn0263006; SERCA.', 'DR   FlyBase; FBgn0266417; ringer.', 'DR   FlyBase; FBgn0013269; Fkbp39.', 'DR   FlyBase; FBgn0014455; Ahcy.', 'DR   FlyBase; FBgn0000591; E(spl)m8-HLH.', 'DR   FlyBase; FBgn0039065; Rad60.', 'DR   FlyBase; FBgn0037728; p23.', 'DR   FlyBase; FBgn0038651; Epg5.', 'DR   FlyBase; FBgn0263133; mEFG1.', 'DR   FlyBase; FBgn0000052; Pfas.', 'DR   FlyBase; FBgn0015011; AhcyL2.', 'DR   FlyBase; FBgn0036529; Pgant8.', 'DR   FlyBase; FBgn0030930; Pgant7.', 'DR   FlyBase; FBgn0010350; Cds.', 'DR   FlyBase; FBgn0039280; Mocs2B.', 'DR   FlyBase; FBgn0034351; rswl.', 'DR   FlyBase; FBgn0263398; Uck.', 'DR   FlyBase; FBgn0262517; Ltn1.', 'DR   FlyBase; FBgn0039936; Gyf.', 'DR   FlyBase; FBgn0016119; ATPsynCF6.', 'DR   FlyBase; FBgn0015805; HDAC1.', 'DR   FlyBase; FBgn0037780; ohgt.', 'DR   FlyBase; FBgn0020312; Tmtc3.', 'DR   FlyBase; FBgn0027780; Aasdh.', 'DR   FlyBase; FBgn0035032; ATPsynF.', 'DR   FlyBase; FBgn0032339; Wdr59.', 'DR   FlyBase; FBgn0037073; Tsr1.', 'DR   FlyBase; FBgn0263852; Dad1.', 'DR   FlyBase; FBgn0037998; Cog1.', 'DR   FlyBase; FBgn0027094; AlaRS.', 'DR   FlyBase; FBgn0036192; Pldn.', 'DR   FlyBase; FBgn0025630; Rtca.', 'DR   FlyBase; FBgn0000053; Gart.', 'DR   FlyBase; FBgn0032671; JMJD4.', 'DR   FlyBase; FBgn0037551; Arl8.', 'DR   FlyBase; FBgn0031589; Naprt.', 'DR   FlyBase; FBgn0036667; kud.', 'DR   FlyBase; FBgn0001258; Ldh.', 'DR   FlyBase; FBgn0035586; Fitm.', 'DR   FlyBase; FBgn0039965; Coa7.', 'DR   FlyBase; FBgn0051956; Pgant4.', 'DR   FlyBase; FBgn0039690; Gnpnat.', 'DR   FlyBase; FBgn0030178; Naxe.', 'DR   FlyBase; FBgn0034802; CNBP.', 'DR   FlyBase; FBgn0042083; Mccc2.', 'DR   FlyBase; FBgn0034129; Parp16.', 'DR   FlyBase; FBgn0036057; Hez.', 'DR   FlyBase; FBgn0003076; Pgm1.', 'DR   FlyBase; FBgn0001128; Gpdh1.', 'DR   FlyBase; FBgn0039139; Mettl3.', 'DR   FlyBase; FBgn0013954; Fkbp12.', 'DR   FlyBase; FBgn0263979; Caf1-55.', 'DR   FlyBase; FBgn0030373; moon.', 'DR   FlyBase; FBgn0014075; Uggt.', 'DR   FlyBase; FBgn0031681; Pgant5.', 'DR   FlyBase; FBgn0035375; Pgant6.', 'DR   FlyBase; FBgn0031530; Pgant2.', 'DR   FlyBase; FBgn0260229; Mocs2A.', 'DR   FlyBase; FBgn0266570; NO66.', 'DR   FlyBase; FBgn0029174; Fkbp59.', 'DR   FlyBase; FBgn0030512; Nadsyn.', 'DR   FlyBase; FBgn0039559; NSD.', 'DR   FlyBase; FBgn0027083; MetRS-m.', 'DR   FlyBase; FBgn0025335; Cpes.', 'DR   FlyBase; FBgn0030364; Lsm12.', 'DR   FlyBase; FBgn0003067; Pepck1.', 'DR   FlyBase; FBgn0035853; UbcE2M.', 'DR   FlyBase; FBgn0034025; Pgant1.', 'DR   FlyBase; FBgn0034894; sigmar.', 'DR   FlyBase; FBgn0038893; Archease.', 'DR   FlyBase; FBgn0004895; FoxL1.', 'DR   FlyBase; FBgn0039296; Sil1.', 'DR   FlyBase; FBgn0051159; mRRF2.', 'DR   FlyBase; FBgn0034982; Naa35.', 'DR   FlyBase; FBgn0037898; Dtd.', 'DR   FlyBase; FBgn0035523; Ctl1.', 'DR   FlyBase; FBgn0259150; OtopLc.', 'DR   FlyBase; FBgn0036300; Pmm2.', 'DR   FlyBase; FBgn0032054; Uba4.', 'DR   FlyBase; FBgn0030966; Suox.', 'DR   FlyBase; FBgn0042185; MCU.', 'DR   FlyBase; FBgn0004888; Scsalpha1.']

107

Exctract information new gene name from the feature_DR1 list.

In [0]:
myl2 = feature_DR1
print(myl2)
oldgene_name = []
for element in myl2:
    m = re.match(r'DR.+[\w.]+;\s[\w.]+;\s+(\w.*)\.', element)
    if m:
        found = m.group(1)
        oldgene_name.append(found)
#oldgene_name
len(oldgene_name)

['DR   FlyBase; FBgn0031670; CG3887.', 'DR   FlyBase; FBgn0031519; CG3326.', 'DR   FlyBase; FBgn0029176; Ef1gamma.', 'DR   FlyBase; FBgn0262116; CG40127.', 'DR   FlyBase; FBgn0034529; CG16742.', 'DR   FlyBase; FBgn0000557; Ef1alpha100E.', 'DR   FlyBase; FBgn0029175; Ext2.', 'DR   FlyBase; FBgn0039637; CG11880.', 'DR   FlyBase; FBgn0031893; CG4495.', 'DR   FlyBase; FBgn0028519; CG4500.', 'DR   FlyBase; FBgn0033316; CG14749.', 'DR   FlyBase; FBgn0261697; tectonic.', 'DR   FlyBase; FBgn0010387; Dbi.', 'DR   FlyBase; FBgn0032393; CG12264.', 'DR   FlyBase; FBgn0000559; EF2.', 'DR   FlyBase; FBgn0032470; CG5142.', 'DR   FlyBase; FBgn0027090; Aats-gln.', 'DR   FlyBase; FBgn0260779; gatA.', 'DR   FlyBase; FBgn0036510; CG7427.', 'DR   FlyBase; FBgn0024227; ial.', 'DR   FlyBase; FBgn0027558; pgant3.', 'DR   FlyBase; FBgn0020513; ade5.', 'DR   FlyBase; FBgn0262619; DNA-ligI.', 'DR   FlyBase; FBgn0038453; CG10326.', 'DR   FlyBase; FBgn0011769; Fdxh.', 'DR   FlyBase; FBgn0263006; Ca-P60A.', 'DR   FlyBase; FBgn0266417; CG45057.', 'DR   FlyBase; FBgn0013269; FK506-bp1.', 'DR   FlyBase; FBgn0014455; Ahcy13.', 'DR   FlyBase; FBgn0000591; E(spl).', 'DR   FlyBase; FBgn0039065; CG4449.', 'DR   FlyBase; FBgn0037728; CG16817.', 'DR   FlyBase; FBgn0038651; CG14299.', 'DR   FlyBase; FBgn0263133; ico.', 'DR   FlyBase; FBgn0000052; ade2.', 'DR   FlyBase; FBgn0015011; Ahcy89E.', 'DR   FlyBase; FBgn0036529; pgant8.', 'DR   FlyBase; FBgn0030930; GalNAc-T2.', 'DR   FlyBase; FBgn0010350; CdsA.', 'DR   FlyBase; FBgn0039280; Mocs2.', 'DR   FlyBase; FBgn0034351; CG5190.', 'DR   FlyBase; FBgn0263398; CG6364.', 'DR   FlyBase; FBgn0262517; l(3)76BDr.', 'DR   FlyBase; FBgn0039936; CG11148.', 'DR   FlyBase; FBgn0016119; ATPsynCf6.', 'DR   FlyBase; FBgn0015805; Rpd3.', 'DR   FlyBase; FBgn0037780; CG3925.', 'DR   FlyBase; FBgn0020312; CG4050.', 'DR   FlyBase; FBgn0027780; U26.', 'DR   FlyBase; FBgn0035032; CG4692.', 'DR   FlyBase; FBgn0032339; CG4705.', 'DR   FlyBase; FBgn0037073; CG7338.', 'DR   FlyBase; FBgn0263852; l(2)k12914.', 'DR   FlyBase; FBgn0037998; CG4848.', 'DR   FlyBase; FBgn0027094; Aats-ala.', 'DR   FlyBase; FBgn0036192; Pallidin.', 'DR   FlyBase; FBgn0025630; CG4061.', 'DR   FlyBase; FBgn0000053; ade3.', 'DR   FlyBase; FBgn0032671; CG7200.', 'DR   FlyBase; FBgn0037551; Gie.', 'DR   FlyBase; FBgn0031589; CG3714.', 'DR   FlyBase; FBgn0036667; CG9669.', 'DR   FlyBase; FBgn0001258; ImpL3.', 'DR   FlyBase; FBgn0035586; CG10671.', 'DR   FlyBase; FBgn0039965; CG13865.', 'DR   FlyBase; FBgn0051956; pgant4.', 'DR   FlyBase; FBgn0039690; CG1969.', 'DR   FlyBase; FBgn0030178; CG2974.', 'DR   FlyBase; FBgn0034802; CG3800.', 'DR   FlyBase; FBgn0042083; CG3267.', 'DR   FlyBase; FBgn0034129; CG15925.', 'DR   FlyBase; FBgn0036057; CG14164.', 'DR   FlyBase; FBgn0003076; Pgm.', 'DR   FlyBase; FBgn0001128; Gpdh.', 'DR   FlyBase; FBgn0039139; Ime4.', 'DR   FlyBase; FBgn0013954; FK506-bp2.', 'DR   FlyBase; FBgn0263979; Caf1.', 'DR   FlyBase; FBgn0030373; CG12721.', 'DR   FlyBase; FBgn0014075; Ugt.', 'DR   FlyBase; FBgn0031681; pgant5.', 'DR   FlyBase; FBgn0035375; pgant6.', 'DR   FlyBase; FBgn0031530; pgant2.', 'DR   FlyBase; FBgn0260229; CG42503.', 'DR   FlyBase; FBgn0266570; CG2982.', 'DR   FlyBase; FBgn0029174; FKBP59.', 'DR   FlyBase; FBgn0030512; CG9940.', 'DR   FlyBase; FBgn0039559; Mes-4.', 'DR   FlyBase; FBgn0027083; Aats-met-m.', 'DR   FlyBase; FBgn0025335; CG4585.', 'DR   FlyBase; FBgn0030364; CG15735.', 'DR   FlyBase; FBgn0003067; Pepck.', 'DR   FlyBase; FBgn0035853; Ubc12.', 'DR   FlyBase; FBgn0034025; GalNAc-T1.', 'DR   FlyBase; FBgn0034894; CG4091.', 'DR   FlyBase; FBgn0038893; CG6353.', 'DR   FlyBase; FBgn0004895; fd64A.', 'DR   FlyBase; FBgn0039296; CG10420.', 'DR   FlyBase; FBgn0051159; EF-G2.', 'DR   FlyBase; FBgn0034982; CG4065.', 'DR   FlyBase; FBgn0037898; CG18643.', 'DR   FlyBase; FBgn0035523; CG1311.', 'DR   FlyBase; FBgn0259150; CG42265.', 'DR   FlyBase; FBgn0036300; CG10688.', 'DR   FlyBase; FBgn0032054; CG13090.', 'DR   FlyBase; FBgn0030966; CG7280.', 'DR   FlyBase; FBgn0042185; CG18769.', 'DR   FlyBase; FBgn0004888; Scsalpha.']

107

In [0]:
import requests, sys
import pandas as pd
urlDR1= oldgene_name
#url_list_oldgene= []
for element in urlDR1:
    #print(element)
    url = 'http://www.uniprot.org/uniprot/?sort=score&desc=&compress=no&query=gene:' + element + '%20AND%20organism:%22Drosophila%20melanogaster%20(Fruit%20fly)%20[7227]%22%20AND%20reviewed:yes&fil=&format=tab&columns=id,database(GeneID),citation,citationmapping'
    #print(a)
    #url_list_oldgene.append(a)
    #print(url_list_oldgene)
    r = requests.get(url) 
        #name = print(gene + '_retrieved.tab')
    with open('retrievedtest.tab', 'a') as outfile:
        outfile.write(r.text)

In [0]:
import pandas as pd
d = {'id': feature_AC, 'DR_old': oldgene_name, 'DR_new': newgene_name, 'New_FlybaseGene': newFGgene_name}
df1 = pd.DataFrame(data=d)
df1

         id        DR_old        DR_new New_FlybaseGene
0    Q9VMV6        CG3887          SelT     FBgn0031670
1    Q9VQN8        CG3326          Fign     FBgn0031519
2    Q9NJH0      Ef1gamma     eEF1gamma     FBgn0029176
3    Q8MSF5       CG40127        RNASEK     FBgn0262116
4    A1ZBW7       CG16742         FAM21     FBgn0034529
5    P05303  Ef1alpha100E    eEF1alpha2     FBgn0000557
6    Q9Y169          Ext2          sotv     FBgn0029175
7    Q9VAP3       CG11880          Ctl2     FBgn0039637
8    A2VEI2        CG4495         MICU1     FBgn0031893
9    Q9V3U0        CG4500           hll     FBgn0028519
10   Q9V4W1       CG14749          Gle1     FBgn0033316
11   Q9VMH0      tectonic          tctn     FBgn0261697
12   P42281           Dbi         Acbp2     FBgn0010387
13   Q9VKD3       CG12264          Nfs1     FBgn0032393
14   P13060           EF2          eEF2     FBgn0000559
15   Q9VK41        CG5142         Ttc30     FBgn0032470
16   Q9Y105      Aats-gln         GlnRS     FBgn0027090
17   Q9VE09          gatA          GatA     FBgn0260779
18   Q9VUQ8        CG7427         SCCRO     FBgn0036510
19   Q9VKN7           ial          aurB     FBgn0024227
20   Q9Y117        pgant3        Pgant3     FBgn0027558
21   Q9I7S8          ade5         Paics     FBgn0020513
22   Q9W1H4      DNA-ligI       DNAlig1     FBgn0262619
23   Q9VES1       CG10326       Arl6IP1     FBgn0038453
24   P37193          Fdxh          Fdx1     FBgn0011769
25   P22700       Ca-P60A         SERCA     FBgn0263006
26   Q9VV43       CG45057        ringer     FBgn0266417
27   P54397     FK506-bp1        Fkbp39     FBgn0013269
28   Q27580        Ahcy13          Ahcy     FBgn0014455
29   P13098        E(spl)  E(spl)m8-HLH     FBgn0000591
..      ...           ...           ...             ...
77   Q9VYQ0       CG12721          moon     FBgn0030373
78   Q09332           Ugt          Uggt     FBgn0014075
79   Q6WV17        pgant5        Pgant5     FBgn0031681
80   Q6WV16        pgant6        Pgant6     FBgn0035375
81   Q6WV19        pgant2        Pgant2     FBgn0031530
82   P0C919       CG42503        Mocs2A     FBgn0260229
83   Q7K4H4        CG2982          NO66     FBgn0266570
84   Q9VL78        FKBP59        Fkbp59     FBgn0029174
85   Q9VYA0        CG9940        Nadsyn     FBgn0030512
86   Q8MT36         Mes-4           NSD     FBgn0039559
87   Q9VFL5    Aats-met-m       MetRS-m     FBgn0027083
88   O77475        CG4585          Cpes     FBgn0025335
89   Q9VYR0       CG15735         Lsm12     FBgn0030364
90   P20007         Pepck        Pepck1     FBgn0003067
91   Q9VSF3         Ubc12        UbcE2M     FBgn0035853
92   Q6WV20     GalNAc-T1        Pgant1     FBgn0034025
93   Q7KVH9        CG4091        sigmar     FBgn0034894
94   Q9VD92        CG6353      Archease     FBgn0038893
95   Q02360         fd64A         FoxL1     FBgn0004895
96   Q9VBV5       CG10420          Sil1     FBgn0039296
97   Q9VCX4         EF-G2         mRRF2     FBgn0051159
98   Q9W1A2        CG4065         Naa35     FBgn0034982
99   Q9VGP0       CG18643           Dtd     FBgn0037898
100  Q9VZE7        CG1311          Ctl1     FBgn0035523
101  B7Z0W9       CG42265        OtopLc     FBgn0259150
102  Q9VTZ6       CG10688          Pmm2     FBgn0036300
103  Q9VLJ8       CG13090          Uba4     FBgn0032054
104  Q9VWP4        CG7280          Suox     FBgn0030966
105  Q8IQ70       CG18769           MCU     FBgn0042185
106  Q94522      Scsalpha     Scsalpha1     FBgn0004888

[107 rows x 4 columns]

In [0]:
df1.to_csv('listgenes.tsv', sep='\t', index=False)

In [0]:
import pandas as pd

df = pd.read_csv('retrievedtest.tab', 
                    sep='\t',
                    header=None,
                    names=['id', 'geneid', 'pmid', 'sp_pmid'],
                    converters={'geneid': lambda x: x.strip(';'), 'pmid': lambda x: x.split('; '), 'sp_pmid': lambda x: x.split('; ')})
df.head()

,id,geneid,pmid,sp_pmid
0,Entry,Cross-reference (GeneID),[PubMed ID],[Mapped PubMed ID]
1,Q9VMV6,33725,"[10731132, 12537572, 12537569]","[10731132, 12537572, 12537569, 23071443, 23319..."
2,Entry,Cross-reference (GeneID),[PubMed ID],[Mapped PubMed ID]
3,Q9VQN8,33544,"[10731132, 12537572, 12537569]","[10731132, 12537572, 12537569, 11309190, 12908..."
4,Entry,Cross-reference (GeneID),[PubMed ID],[Mapped PubMed ID]

In [0]:
a = df.iloc[1::2]
a.head()

,id,geneid,pmid,sp_pmid
1,Q9VMV6,33725,"[10731132, 12537572, 12537569]","[10731132, 12537572, 12537569, 23071443, 23319..."
3,Q9VQN8,33544,"[10731132, 12537572, 12537569]","[10731132, 12537572, 12537569, 11309190, 12908..."
5,Q9NJH0,44791,"[10731132, 12537572, 12537569, ]","[10731132, 12537572, 12537569, 10908586, 11583..."
7,Q8MSF5,3355016,"[10731132, 12537572, 12537569]","[10731132, 12537572, 12537569, 15020470, 15612..."
9,A1ZBW7,37331,"[10731132, 12537572, 12537569, 18327897, 17372...","[10731132, 12537572, 12537569, 18327897, 17372..."

In [0]:
a.to_csv('listgenesretrieved.tsv', sep='\t', index=False)

In [0]:

import pandas as pd
pubtator = pd.read_csv('gene2pubtator',
                        sep='\t',
                        header=0,
                        names=['pubtator_pmid', 'geneid', 'mentions', 'source'],
                        usecols=['pubtator_pmid', 'geneid', 'mentions'],
                        dtype=str)

pubtator.head()

  pubtator_pmid geneid                 mentions
0       1000011   7356  blastokinin|uteroglobin
1       1000045   2006             tropoelastin
2       1000084   7018              transferrin
3       1000327   4199     malate dehydrogenase
4       1000392   4151                myoglobin

In [0]:
pubtator[pubtator.pubtator_pmid == '27693235']

        pubtator_pmid geneid mentions
7498437      27693235   1603     Dad1
7498438      27693235  42059    dDad1

In [0]:
merged = df.merge(pubtator, on='geneid')

In [0]:
merged.head()

,id,geneid,pmid,sp_pmid,pubtator_pmid,mentions
0,Q9NJH0,44791,"[10731132, 12537572, 12537569, ]","[10731132, 12537572, 12537569, 10908586, 11583...",19841092,EF1gamma
1,Q9NJH0,44791,"[10731132, 12537572, 12537569, ]","[10731132, 12537572, 12537569, 10908586, 11583...",24163433,EF1y
2,Q8MSF5,3355016,"[10731132, 12537572, 12537569]","[10731132, 12537572, 12537569, 15020470, 15612...",20382826,CG40127
3,Q8MSF5,3355016,"[10731132, 12537572, 12537569]","[10731132, 12537572, 12537569, 15020470, 15612...",26056282,dRNASEK
4,P05303,43736,"[3131735, 10731132, 12537572, 3135536]","[3131735, 10731132, 12537572, 3135536, 1053078...",22666323,EF1a-100E

Eliminate any PMIDs which are already annotated in SwissProt, and just show "new" references.

Use the pandas "apply" method to filter out any Pubtator PMIDs which are also in the SwissProt PMID list.

In [0]:
new_refs = merged[merged.apply(lambda x: x.pubtator_pmid not in x.pmid, axis=1)].reset_index(drop=True)
new_refs.head()

,id,geneid,pmid,sp_pmid,pubtator_pmid,mentions
0,Q9NJH0,44791,"[10731132, 12537572, 12537569, ]","[10731132, 12537572, 12537569, 10908586, 11583...",19841092,EF1gamma
1,Q9NJH0,44791,"[10731132, 12537572, 12537569, ]","[10731132, 12537572, 12537569, 10908586, 11583...",24163433,EF1y
2,Q8MSF5,3355016,"[10731132, 12537572, 12537569]","[10731132, 12537572, 12537569, 15020470, 15612...",20382826,CG40127
3,Q8MSF5,3355016,"[10731132, 12537572, 12537569]","[10731132, 12537572, 12537569, 15020470, 15612...",26056282,dRNASEK
4,P05303,43736,"[3131735, 10731132, 12537572, 3135536]","[3131735, 10731132, 12537572, 3135536, 1053078...",22666323,EF1a-100E

In [0]:
list(new_refs)

['id', 'geneid', 'pmid', 'sp_pmid', 'pubtator_pmid', 'mentions']

In [0]:
new_refs.drop(['sp_pmid', 'mentions'], axis=1, inplace=True)
new_refs.head()

       id   geneid                                    pmid pubtator_pmid
0  Q9NJH0    44791        [10731132, 12537572, 12537569, ]      19841092
1  Q9NJH0    44791        [10731132, 12537572, 12537569, ]      24163433
2  Q8MSF5  3355016          [10731132, 12537572, 12537569]      20382826
3  Q8MSF5  3355016          [10731132, 12537572, 12537569]      26056282
4  P05303    43736  [3131735, 10731132, 12537572, 3135536]      22666323

In [0]:
merged2 = new_refs.merge(df1, on='id')
merged2.head()

,id,geneid,pmid,pubtator_pmid,DR_old,DR_new,New_FlybaseGene
0,Q9NJH0,44791,"[10731132, 12537572, 12537569, ]",19841092,Ef1gamma,eEF1gamma,FBgn0029176
1,Q9NJH0,44791,"[10731132, 12537572, 12537569, ]",24163433,Ef1gamma,eEF1gamma,FBgn0029176
2,Q8MSF5,3355016,"[10731132, 12537572, 12537569]",20382826,CG40127,RNASEK,FBgn0262116
3,Q8MSF5,3355016,"[10731132, 12537572, 12537569]",26056282,CG40127,RNASEK,FBgn0262116
4,P05303,43736,"[3131735, 10731132, 12537572, 3135536]",22666323,Ef1alpha100E,eEF1alpha2,FBgn0000557

http://www.uniprot.org/uniprot/?sort=score&desc=&compress=no&query=id:Q9V3N8&format=tab&columns=id,entry%20name,reviewed,protein%20names,genes,organism,length,comment(FUNCTION),citation,citationmapping

In [0]:
count = merged2.groupby('geneid')['id'].transform('count')
count.head()

0    2
1    2
2    2
3    2
4    5
Name: id, dtype: int64

In [0]:
merged2['count'] = count
merged2.head()

,id,geneid,pmid,pubtator_pmid,DR_old,DR_new,New_FlybaseGene,count
0,Q9NJH0,44791,"[10731132, 12537572, 12537569, ]",19841092,Ef1gamma,eEF1gamma,FBgn0029176,2
1,Q9NJH0,44791,"[10731132, 12537572, 12537569, ]",24163433,Ef1gamma,eEF1gamma,FBgn0029176,2
2,Q8MSF5,3355016,"[10731132, 12537572, 12537569]",20382826,CG40127,RNASEK,FBgn0262116,2
3,Q8MSF5,3355016,"[10731132, 12537572, 12537569]",26056282,CG40127,RNASEK,FBgn0262116,2
4,P05303,43736,"[3131735, 10731132, 12537572, 3135536]",22666323,Ef1alpha100E,eEF1alpha2,FBgn0000557,5

In [0]:
merged2.sort_values(by=['count']).to_csv('list.tsv', sep='\t', index=False)

In [0]:
#merged2.to_csv('list.tsv', sep='\t', index=False)

In [0]:
merged2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1192 entries, 0 to 1191
Data columns (total 8 columns):
id                 1192 non-null object
geneid             1192 non-null object
pmid               1192 non-null object
pubtator_pmid      1192 non-null object
DR_old             1192 non-null object
DR_new             1192 non-null object
New_FlybaseGene    1192 non-null object
count              1192 non-null int64
dtypes: int64(1), object(7)
memory usage: 83.8+ KB